# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class WistiaCli < Formula
  desc "Data API: Wistia Data API"
  homepage "https://github.com/wistia/wistia-cli"
  version "2026.5.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/wistia/wistia-cli/releases/download/v2026.5.0/wistia_Darwin_x86_64.tar.gz"
      sha256 "24e9d6f828aa51c21c158afa8f3f1947a83ce84eff0425c110880a8740e7a6b3"

      define_method(:install) do
        bin.install "wistia"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/wistia/wistia-cli/releases/download/v2026.5.0/wistia_Darwin_arm64.tar.gz"
      sha256 "aeb187e8a160f201eb8dfcd17af02ae57c5f5a2998138af87e22785d56e83c1f"

      define_method(:install) do
        bin.install "wistia"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/wistia/wistia-cli/releases/download/v2026.5.0/wistia_Linux_x86_64.tar.gz"
      sha256 "83a37123cb8259c306401d2438c98ca114c706f686a2352df16dd10d611cbbea"
      define_method(:install) do
        bin.install "wistia"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/wistia/wistia-cli/releases/download/v2026.5.0/wistia_Linux_arm64.tar.gz"
      sha256 "30f1f9bfa63157aac04b93f353812e415a2de704ab506b29f140a9d6d672d083"
      define_method(:install) do
        bin.install "wistia"
      end
    end
  end
end
